name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust build ${{ matrix.toolchain }} on ${{ matrix.os }}
    
    strategy:
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --release
      - if: ${{ matrix.os == 'macos-latest' }}
        name: Build macOS bundle
        run: |
          cargo install cargo-bundle
          cargo bundle --release
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Install cargo-appimage
        run: |
          sudo curl -L https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -o /usr/local/bin/appimagetool
          cargo install cargo-appimage
          cp thermal-cat-logo-512px.png icon.png
          cargo appimage

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: ${{ matrix.os }}-release
          path: target/release/thermal-cat.exe
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: ${{ matrix.os }}-release
          path: "target/release/bundle/osx"
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: ${{ matrix.os }}-release
          path: |
            target/release/thermal-cat
            target/appimage/thermal-cat.AppImage
          
  